apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx # nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      run: nginx # app: nginx
  template:
    metadata:
      labels:
        run: nginx # app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        resources:
          requests:
            cpu: 400m
            memory: 60Mi
          limits:
            cpu: 400m
            memory: 60Mi
        ports:
        - containerPort: 80
