apiVersion: v1
data:
  # secrets are base 64 encoded
  password: Y3V0b2Zmcw==
  username: dG9iaWFz
kind: Secret
metadata:
  creationTimestamp: "2022-06-20T19:49:56Z"
  name: hush-hush
  namespace: default
  resourceVersion: "51831"
  uid: 93e8d6d1-4c7f-4868-b146-32d1eb02b0a6
type: Opaque

# Command example to create secret:
# k create secret generic hush-hush \
#   --from-literal=username=tobias \
#   --from-literal=password=cutoffs
